pre-release-commit-message = "release"
no-dev-version = true
tag-message = "{{tag_name}}"
tag-name = "{{prefix}}v{{version}}"
sign-tag = true
consolidate-commits = true
consolidate-pushes = true
allow-branch = ["main"]