pre-release-commit-message = "Release {{version}}"
no-dev-version = true
tag-message = "{{tag_name}}"
tag-name = "{{prefix}}v{{version}}"
consolidate-commits = true
consolidate-pushes = true
allow-branch = ["main"]